### ISSUE TITLE
[Feature Request] Support for "module", "es2015", "typings" fields

### ISSUE THREAD

**Issue by itsdevdom** [abraham/pkg-ok#1]
Hey, it would be really awesome to not only check for the "main" file, but also for the files defined in the "module", "es2015" as well as "typings" fields. For example, this would be especially interesting for people (like me) developing Angular 2+ libraries - which (at least since Angular 4) also contain the fields named above.

Do you have time to extend the library? Or should I give it a try and open a PR?

**Comment by typicode** [comment]
Hi @dominique-mueller,

Good idea, working on it on `next` branch :)
Hope to be able to release something soon.

**Comment by typicode** [comment]
It's published (`v1.1.0`) :wink: :tada: 

I preferred to avoid making assumptions on which non-standard should be checked by default, instead `pkg-ok` now accepts additional fields as arguments.

**Comment by itsdevdom** [comment]
Awesome! Works like a charm!
