### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by ernscht** [abraham/pkg-ok#23]
Hi typicode
We use pkg-ok regularly. Thanks for the tool.
But since two years it has not been maintained. Will you not update the tool anymore?

**Comment by axaq** [comment]
Seems like it. I sent a pull request ( #27 ) updating meow version to get rid of npm vulnerabilities. Hopefully @typicode can have a look and accept soon or let us contribute since this library seems to be still used by many.

**Comment by abraham** [comment]
I've [updated a fork](https://github.com/abraham/pkg-ok) with:
* Node.js 12+ support
* Converted to ESM
* Updated dependencies

```sh
npm uninstall pkg-ok
npm install @abraham/pkg-ok --save-dev
```

**Comment by typicode** [comment]
Looks awesome! :clap: :)

I personally don't use pkg-ok anymore and I think this fork should replace the current one. How would you like to proceed?

**Comment by abraham** [comment]
With the assumption that impact on users should be minimized and you don't want to be involved anymore I'd suggest the following:

1. [Add](https://docs.npmjs.com/cli/v8/commands/npm-owner) `abraham` on npm.
2. [Transfer](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) to `abraham` on GitHub.
3. Make sure everything works for a six months.
4. [Remove](https://docs.npmjs.com/cli/v8/commands/npm-owner) `typicode` from GitHub.
5. [Remove](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/removing-a-collaborator-from-a-personal-repository) `typicode` from npm.

How does that sound?

**Comment by typicode** [comment]
I've added you to npm but I can't transfer the repo:
`abraham already has a repository in the typicode/pkg-ok network`

**Comment by abraham** [comment]
🤣 That's fun. I'll look into options this weekend.

**Comment by abraham** [comment]
I had GitHub detach my fork. You should be able to transfer now.

**Comment by typicode** [comment]
> You should be able to transfer now

Done (it's in progress according to GitHub)

**Comment by abraham** [comment]
Great! I've merged the updates from the fork and published a new prerelease.

```sh
npm install pkg-ok@next --save-dev
```
