### ISSUE TITLE
Browser field (and others?) may need refinement

### ISSUE THREAD

**Issue by typicode** [abraham/pkg-ok#9]
Browser field (and others?) may need to refined:
https://twitter.com/AndaristRake/status/1048164567698886656

Thanks a lot to @Andarist for pointing that out! :+1:

**Comment by Andarist** [comment]
Im not sure if the thing i have said about relative paths in browser field is common for all tools, but I had to fix it at least once for webpack - https://github.com/andreypopp/react-textarea-autosize/commit/866612508d248c592c3ffe4186306cff4c0c6af7

You might want to tag this issue as Hacktoberfest.

**Comment by typicode** [comment]
Tagged 🎃

**Comment by HeroProtagonist** [comment]
I will have a small PR for this later today :)

**Comment by typicode** [comment]
@Andarist you mentioned that not all fields can be objects. Do you know/remember which ones?

**Comment by Andarist** [comment]
at least main & module, **I think** bin can be an object, browser can be an object for sure, not sure about types, typings & es2015
